rmdir /S /Q "..\package"

mkdir "..\package\SCFF-DirectShow-Filter-x86"
mkdir "..\package\SCFF-DirectShow-Filter-amd64"

copy /y "..\dist\Release\scff-app.exe" "..\package\SCFF-DirectShow-Filter-x86"
copy /y "..\dist\Release-x86\*.dll" "..\package\SCFF-DirectShow-Filter-x86"
copy /y "..\dist\Release-x86\*.ax" "..\package\SCFF-DirectShow-Filter-x86"
copy /y "regsvrex32.exe" "..\package\SCFF-DirectShow-Filter-x86"
copy /y "packaging\Microsoft .NET Framework 4 Client Profile.url" "..\package\SCFF-DirectShow-Filter-x86"
copy /y "packaging\VC2010SP1 Redistributable Package (x86).url" "..\package\SCFF-DirectShow-Filter-x86"
copy /y "packaging\install-x86.bat" "..\package\SCFF-DirectShow-Filter-x86"
copy /y "packaging\uninstall-x86.bat" "..\package\SCFF-DirectShow-Filter-x86"
copy /y "..\README.md" "..\package\SCFF-DirectShow-Filter-x86"
copy /y "..\LICENSE" "..\package\SCFF-DirectShow-Filter-x86"

copy /y "..\dist\Release\scff-app.exe" "..\package\SCFF-DirectShow-Filter-amd64"
copy /y "..\dist\Release-amd64\*.dll" "..\package\SCFF-DirectShow-Filter-amd64"
copy /y "..\dist\Release-amd64\*.ax" "..\package\SCFF-DirectShow-Filter-amd64"
copy /y "regsvrex64.exe" "..\package\SCFF-DirectShow-Filter-amd64"
copy /y "packaging\Microsoft .NET Framework 4 Client Profile.url" "..\package\SCFF-DirectShow-Filter-amd64"
copy /y "packaging\VC2010SP1 Redistributable Package (x64).url" "..\package\SCFF-DirectShow-Filter-amd64"
copy /y "packaging\install-amd64.bat" "..\package\SCFF-DirectShow-Filter-amd64"
copy /y "packaging\uninstall-amd64.bat" "..\package\SCFF-DirectShow-Filter-amd64"
copy /y "..\README.md" "..\package\SCFF-DirectShow-Filter-amd64"
copy /y "..\LICENSE" "..\package\SCFF-DirectShow-Filter-amd64"
